"""ss

Revision ID: 4ccf50c11a74
Revises: 
Create Date: 2025-10-18 19:26:07.471244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ccf50c11a74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number_country_code', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('parent_phone_number_country_code', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('parent_phone_number_country_code')
        batch_op.drop_column('phone_number_country_code')

    # ### end Alembic commands ###
