"""send wp to certain hws

Revision ID: 57291bc6c088
Revises: 
Create Date: 2025-10-18 20:22:34.374387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57291bc6c088'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_whatsapp', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('parent_whatsapp', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('parent_whatsapp')
        batch_op.drop_column('student_whatsapp')

    # ### end Alembic commands ###
