"""corrected

Revision ID: 74921a4c0395
Revises: 57291bc6c088
Create Date: 2025-10-18 21:04:28.490615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74921a4c0395'
down_revision = '57291bc6c088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('corrected', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('corrected')

    # ### end Alembic commands ###
