"""Submissions updates

Revision ID: 945f35134e36
Revises: 5483dd39db71
Create Date: 2025-10-19 09:35:41.539358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945f35134e36'
down_revision = '5483dd39db71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('close_after_deadline', sa.Boolean(), nullable=True))

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['reviewed_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reviewed_by_id')
        batch_op.drop_column('reviewed')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('close_after_deadline')

    # ### end Alembic commands ###
