"""country code

Revision ID: bf20da9d1813
Revises: 74921a4c0395
Create Date: 2025-10-18 22:24:51.145309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf20da9d1813'
down_revision = '74921a4c0395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number_country_code', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('parent_phone_number_country_code', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('parent_phone_number_country_code')
        batch_op.drop_column('phone_number_country_code')

    # ### end Alembic commands ###
