"""ss

Revision ID: caa6cda2abb9
Revises: 
Create Date: 2025-10-19 20:00:20.268303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caa6cda2abb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correction_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('review_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('corrected_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['corrected_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('corrected_by_id')
        batch_op.drop_column('review_date')
        batch_op.drop_column('correction_date')

    # ### end Alembic commands ###
